trigger: none

parameters:
  - name: Version
    default: '1.0.0'

variables:
  - name: projectName
    value: "PackageUploader"
  - name: buildConfiguration
    value: "release"
  - name: version
    value: ${{ parameters.Version }}

stages:
  - stage: Build
    displayName: 

    jobs:
      - job: BuildWindows
        displayName: Build win-x64
        pool:
          vmImage: windows-latest

        variables:
          - name: buildRuntime
            value: "win-x64"

        steps:
        - task: NuGetAuthenticate@1

        - task: DotNetCoreCLI@2
          displayName: 'dotnet publish'
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: './src/PackageUploader.Application/PackageUploader.Application.csproj'
            arguments: '--self-contained -o $(Build.BinariesDirectory) -p:Version=$(version) -r $(buildRuntime) -c $(buildConfiguration)'
            zipAfterPublish: false
            modifyOutputPath: false

        - task: ArchiveFiles@2
          displayName: 'Zip files to Staging directory'
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(projectName).$(version).$(buildRuntime).zip'
            replaceExistingArchive: true

        - task: PublishPipelineArtifact@1
          displayName: 'publish artifact to pipeline'
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifact: '$(projectName).$(buildRuntime)'
            publishLocation: 'pipeline'

      - job: BuildLinux
        displayName: Build linux-x64
        pool:
          vmImage: ubuntu-latest

        variables:
          - name: buildRuntime
            value: "linux-x64"

        steps:
        - task: NuGetAuthenticate@1

        - task: DotNetCoreCLI@2
          displayName: 'dotnet publish'
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: './src/PackageUploader.Application/PackageUploader.Application.csproj'
            arguments: '--self-contained -o $(Build.BinariesDirectory) -p:Version=$(version) -r $(buildRuntime) -c $(buildConfiguration)'
            zipAfterPublish: false
            modifyOutputPath: false

        - task: ArchiveFiles@2
          displayName: 'Zip files to Staging directory'
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(projectName).$(version).$(buildRuntime).zip'
            replaceExistingArchive: true

        - task: PublishPipelineArtifact@1
          displayName: 'publish artifact to pipeline'
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifact: '$(projectName).$(buildRuntime)'
            publishLocation: 'pipeline'